// <auto-generated />
using GestaoLivrosApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GestaoLivrosApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20221212120406_InsertBooks")]
    partial class InsertBooks
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GestaoLivrosApi.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Isbn")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "José Rodrigues dos Santos",
                            Isbn = 9789897776168L,
                            Name = "A Mulher do Dragão Vermelho",
                            Price = 22.5
                        },
                        new
                        {
                            Id = 2,
                            Author = "Anne Jacobs",
                            Isbn = 9789897776342L,
                            Name = "As Filhas da Vila dos Tecidos",
                            Price = 19.899999999999999
                        },
                        new
                        {
                            Id = 3,
                            Author = "Nicholas Sparks",
                            Isbn = 9789892355214L,
                            Name = "Um Sonho Só Nosso",
                            Price = 18.899999999999999
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
