// <auto-generated />
using GestaoLivrosApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GestaoLivrosApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230111143726_updateInicialData")]
    partial class updateInicialData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GestaoLivrosApi.Models.Authors.Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("isDeleted")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Country = "EUA",
                            Image = "https://images.wook.pt/getresourcesservlet/GetResource?Sfm+v10t8OzUnIiam5LiwEo0hAmBYW4YBPscgCFrN6o=",
                            Name = "John Grisham",
                            isDeleted = false
                        },
                        new
                        {
                            Id = 2,
                            Country = "Portugal",
                            Image = "https://images.wook.pt/getresourcesservlet/GetResource?ffOwOOeajYEkMMAJu4eRVE+b1GsFCZd7vCu07LSZze4=",
                            Name = "José Rodrigues dos Santos",
                            isDeleted = false
                        },
                        new
                        {
                            Id = 3,
                            Country = "Alemanha",
                            Image = "https://images.wook.pt/getresourcesservlet/GetResource?dMwB1EC9gK3QmYJxSzq1GslBjIWP8EwCWv82I5JH6Lg=",
                            Name = "Anne Jacobs",
                            isDeleted = false
                        },
                        new
                        {
                            Id = 4,
                            Country = "Reino Unido",
                            Image = "https://s2.glbimg.com/KMWZv9gzUfGw3xUruf2lRIys0Nw=/0x0:2359x3108/984x0/smart/filters:strip_icc()/i.s3.glbimg.com/v1/AUTH_ba3db981e6d14e54bb84be31c923b00c/internal_photos/bs/2022/S/O/83FSniQd6ODv2Pj0H3Lg/dolly-alderton-c-alexandra-cameron.jpg",
                            Name = "Dolly Alderton",
                            isDeleted = false
                        },
                        new
                        {
                            Id = 5,
                            Country = "EUA",
                            Image = "https://images.wook.pt/getresourcesservlet/GetResource?T0mxwoPX8/4+kKBb/GgmzXsvI8fHjBDhGQUR+LmCP4c=",
                            Name = "Colleen Hoover",
                            isDeleted = false
                        },
                        new
                        {
                            Id = 6,
                            Country = "EUA",
                            Image = "https://d28hgpri8am2if.cloudfront.net/author_images/5806082/tracy-deonn-142982529.jpg",
                            Name = "Tracy Deonn",
                            isDeleted = false
                        },
                        new
                        {
                            Id = 7,
                            Country = "França",
                            Image = "https://images.wook.pt/getresourcesservlet/GetResource?mo7QMU8M1/9mmROOAhHATQuUA8f8pMVv8eiir9F8GXc=",
                            Name = "Antoine de Saint-Exupéry",
                            isDeleted = false
                        },
                        new
                        {
                            Id = 8,
                            Country = "EUA",
                            Image = "https://images.wook.pt/getresourcesservlet/GetResource?MvyciI4blwAnOYsiaw1/EYyLTlI26KopmjdP/AyYS5s=",
                            Name = "Taylor Jenkins Reid",
                            isDeleted = false
                        },
                        new
                        {
                            Id = 9,
                            Country = "EUA",
                            Image = "https://images.wook.pt/getresourcesservlet/GetResource?25hy/3TG6A7z4fbZlSI7qz/0WSko+85dOXugaUyx5QY=",
                            Name = "Holly Black",
                            isDeleted = false
                        },
                        new
                        {
                            Id = 10,
                            Country = "EUA",
                            Image = "https://images.wook.pt/getresourcesservlet/GetResource?hhwHlwLEt4Trc15G3MdfT5IdgAztEU3kKGyaWWAH9dA=",
                            Name = "Nicholas Sparks",
                            isDeleted = false
                        });
                });

            modelBuilder.Entity("GestaoLivrosApi.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Isbn")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<bool>("isDeleted")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("Isbn")
                        .IsUnique();

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorId = 2,
                            Image = "https://img.wook.pt/images/a-mulher-do-dragao-vermelho-jose-rodrigues-dos-santos/MXwyNzQyMjE4NXwyMzc4Njg5MHwxNjYzNTc3MzY4MDAwfHdlYnA=/550x",
                            Isbn = 9789897776168L,
                            Name = "A Mulher do Dragão Vermelho",
                            Price = 22.5,
                            isDeleted = false
                        },
                        new
                        {
                            Id = 2,
                            AuthorId = 3,
                            Image = "https://img.wook.pt/images/as-filhas-da-vila-dos-tecidos-anne-jacobs/MXwyNzc0OTYyNnwyNDEyMzk5MHwxNjY1Mzg3MzI5MDAwfHdlYnA=/550x",
                            Isbn = 9789897776342L,
                            Name = "As Filhas da Vila dos Tecidos",
                            Price = 19.899999999999999,
                            isDeleted = false
                        },
                        new
                        {
                            Id = 3,
                            AuthorId = 10,
                            Image = "https://img.wook.pt/images/um-sonho-so-nosso-nicholas-sparks/MXwyNzM0ODM4M3wyMzcwMDU2NXwxNjYxNDQyMjQwMDAwfHdlYnA=/550x",
                            Isbn = 9789892355214L,
                            Name = "Um Sonho Só Nosso",
                            Price = 18.899999999999999,
                            isDeleted = false
                        },
                        new
                        {
                            Id = 4,
                            AuthorId = 7,
                            Image = "https://almedinanet.b-cdn.net/media/catalog/product/cache/10f519365b01716ddb90abc57de5a837/9/7/9789723718928_1587465282.jpg",
                            Isbn = 9789723718928L,
                            Name = "O Principezinho",
                            Price = 5.5,
                            isDeleted = false
                        },
                        new
                        {
                            Id = 5,
                            AuthorId = 1,
                            Image = "https://img.wook.pt/images/a-lista-do-juiz-john-grisham/MXwyNjczODMxOXwyMzAyMTA2MHwxNjY1MTQwMzgyMDAwfHdlYnA=/550x",
                            Isbn = 9789722543606L,
                            Name = "A Lista do Juizes",
                            Price = 18.989999999999998,
                            isDeleted = false
                        },
                        new
                        {
                            Id = 6,
                            AuthorId = 6,
                            Image = "https://img.wook.pt/images/lendarios-tracy-deonn/MXwyNzYxOTY2MHwyMzk5Mjg2M3wxNjY0NzkwODA4MDAwfHdlYnA=/550x",
                            Isbn = 9789898860019L,
                            Name = "Lendários",
                            Price = 22.0,
                            isDeleted = false
                        },
                        new
                        {
                            Id = 7,
                            AuthorId = 4,
                            Image = "https://img.wook.pt/images/estas-ai-dolly-alderton/MXwyNDY4MjQ5MnwyMDgyNzcwOXwxNjE1ODI5NDA5MDAwfHdlYnA=/550x",
                            Isbn = 9789899039414L,
                            Name = "Estás aí?",
                            Price = 17.5,
                            isDeleted = false
                        },
                        new
                        {
                            Id = 8,
                            AuthorId = 5,
                            Image = "https://img.wook.pt/images/layla-colleen-hoover/MXwyNDk3Mzc1M3wyMTE1OTAxNnwxNjUwMjcwMjczMDAwfHdlYnA=/550x",
                            Isbn = 9789895645206L,
                            Name = "Layla",
                            Price = 19.949999999999999,
                            isDeleted = false
                        },
                        new
                        {
                            Id = 9,
                            AuthorId = 8,
                            Image = "https://img.wook.pt/images/os-sete-maridos-de-evelyn-hugo-taylor-jenkins-reid/MXwyNDY5NTU5OXwyMDg0NTI3NnwxNjY0MTc3MzM5MDAwfHdlYnA=/550x",
                            Isbn = 9789895644513L,
                            Name = "Os Sete Maridos de Evelyn Hugo",
                            Price = 20.949999999999999,
                            isDeleted = false
                        },
                        new
                        {
                            Id = 10,
                            AuthorId = 9,
                            Image = "https://img.wook.pt/images/gata-branca-holly-black/MXwxNjA0NTg3OXwxMTU5MDkxNHwxNDE1NjE3MDI0MDAwfHdlYnA=/550x",
                            Isbn = 9789722354158L,
                            Name = "Gata Branca",
                            Price = 16.899999999999999,
                            isDeleted = false
                        });
                });

            modelBuilder.Entity("GestaoLivrosApi.Models.Book", b =>
                {
                    b.HasOne("GestaoLivrosApi.Models.Authors.Author", "Author")
                        .WithMany("Books")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");
                });

            modelBuilder.Entity("GestaoLivrosApi.Models.Authors.Author", b =>
                {
                    b.Navigation("Books");
                });
#pragma warning restore 612, 618
        }
    }
}
